---
apiVersion: v1
kind: Service
metadata:
  name: web-internal
  namespace: {{ NAMESPACE }}
  labels:
    app: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000